package rules;

import fitness.health.model.User;
import fitness.health.model.Exercise;
import fitness.health.model.Injury;
import java.util.List;
import fitness.health.events.ExercisesWhichUseInjuredPartsFiltered;

rule "Filter exercise 2 that use injured part"
    when
        $u: User( $injuries: injuries, $injuries.size != 0)
        $allExercises: List() from collect(Exercise())
    then
        List<Exercise> all = $u.updateExercisesByInjuries($allExercises);
        all.stream().forEach(e -> delete(e));
        modify($u) { removeFirstInjury(); };
end

rule "Empty injuries"
    when
        $u: User( $injuries: injuries, $injuries.size == 0)
        not ExercisesWhichUseInjuredPartsFiltered(userId == $u.id) 
    then
        insert (new ExercisesWhichUseInjuredPartsFiltered($u.getId()));
end