package rules;

import fitness.health.model.User;
import fitness.health.model.enums.Gender;

rule "Classify Gender Constant - Female"
    when
        $u: User( gender == Gender.FEMALE )
    then
        $u.setGenderCoefficient(-161);
        update($u);
end

rule "Classify Gender Constant - Male"
    when
        $u: User( gender == Gender.MALE )
    then
        $u.setGenderCoefficient(5);
        update($u);
end